#!/usr/bin/env python3
"""Generates GamePedia/Shared/Localization/L10nProduct22.swift.

Why this exists instead of the repository's SwiftGen config
-----------------------------------------------------------
`SwiftGen/swiftgen.yml` does not run against the SwiftGen available here
(6.6.3): its input path does not resolve, and pointing it at the localization
directory fails with "Duplicate file of the same type for table Localizable"
because four `.lproj` folders declare the same table. Worse, when it is coaxed
into running, its `structured-swift5` output is a different API shape from the
committed `L10n.swift` — `L10n.Localizable.appName` with a `fallback:`
argument, versus the committed `L10n.App.name` — so regenerating would rewrite
every one of the ~500 existing call sites. The committed `L10n.swift` and
`Localizable.strings` have also drifted (three `common.button.*` keys exist in
the strings but not in the Swift), which means no generator can reproduce the
committed file exactly.

So the existing `L10n.swift` is left alone, and the Product 2.2 keys get their
own generated file in the same shape and with the same `L10n.tr` entry point.
Nothing here is hand-written: edit the `.strings` files and re-run

    python3 scripts/generate-product22-l10n.py

Only the `product22.` prefix is read, so the file cannot pick up unrelated keys.
"""
from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "GamePedia/Resources/Localization/ko.lproj/Localizable.strings")
OUTPUT = os.path.join(ROOT, "GamePedia/Shared/Localization/L10nProduct22.swift")
LANGUAGES = ("ko", "en", "ja", "zh-Hans")
PREFIX = "product22."

ENTRY = re.compile(r'^"([^"]+)"\s*=\s*"(.*)";\s*$')


def read_keys(path: str) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            match = ENTRY.match(line.strip())
            if match and match.group(1).startswith(PREFIX):
                entries.append((match.group(1), match.group(2)))
    return entries


def check_parity(reference: list[tuple[str, str]]) -> list[str]:
    """Every language must define exactly the same key set."""
    problems: list[str] = []
    expected = [key for key, _ in reference]
    for language in LANGUAGES:
        path = os.path.join(
            ROOT, "GamePedia/Resources/Localization", f"{language}.lproj/Localizable.strings"
        )
        actual = [key for key, _ in read_keys(path)]
        missing = set(expected) - set(actual)
        extra = set(actual) - set(expected)
        if missing:
            problems.append(f"{language} is missing: {', '.join(sorted(missing))}")
        if extra:
            problems.append(f"{language} has unexpected: {', '.join(sorted(extra))}")
    return problems


def upper_first(text: str) -> str:
    return text[:1].upper() + text[1:]


def lower_first(text: str) -> str:
    return text[:1].lower() + text[1:]


class Node:
    def __init__(self) -> None:
        self.children: dict[str, "Node"] = {}
        self.leaves: list[tuple[str, str, str]] = []  # (member, full key, comment)


def build_tree(entries: list[tuple[str, str]]) -> Node:
    root = Node()
    for key, value in entries:
        # The "product22" prefix is kept as the root enum, so everything lands
        # under L10n.Product22 and cannot collide with an existing L10n member.
        parts = [upper_first(key.split(".")[0])] + key.split(".")[1:]
        node = root
        for part in parts[:-1]:
            node = node.children.setdefault(upper_first(part), Node())
        node.leaves.append((lower_first(parts[-1]), key, value))
    return root


def render(node: Node, indent: int, out: list[str]) -> None:
    pad = "  " * indent
    for member, key, comment in node.leaves:
        out.append(f"{pad}/// {comment}")
        out.append(f'{pad}static let {member} = L10n.tr("Localizable", "{key}")')
    for index, (name, child) in enumerate(node.children.items()):
        if node.leaves or index > 0:
            out.append("")
        out.append(f"{pad}enum {name} {{")
        render(child, indent + 1, out)
        out.append(f"{pad}}}")


HEADER = """// swiftlint:disable all
// Generated by scripts/generate-product22-l10n.py — do not edit by hand.
//
// Product 2.2 UI strings. Regenerate after editing
// GamePedia/Resources/Localization/<lang>.lproj/Localizable.strings:
//
//     python3 scripts/generate-product22-l10n.py
//
// The script reads only keys prefixed "product22." and fails if the four
// languages do not declare exactly the same key set. See the script's own
// header for why the repository's SwiftGen config is not used here.
//
// UI chrome only. Game titles, developer names, platform names and article
// headlines are server content and must never be routed through L10n.

import Foundation

extension L10n {
"""

FOOTER = """}

// swiftlint:enable all
"""


def main() -> int:
    entries = read_keys(SOURCE)
    if not entries:
        print("no product22.* keys found", file=sys.stderr)
        return 1

    problems = check_parity(entries)
    if problems:
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        return 1

    body: list[str] = []
    render(build_tree(entries), 1, body)

    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write(HEADER)
        handle.write("\n".join(body).rstrip() + "\n")
        handle.write(FOOTER)

    print(f"wrote {OUTPUT} ({len(entries)} keys across {len(LANGUAGES)} languages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
