// swiftlint:disable all
// Generated by scripts/generate-product22-l10n.py — do not edit by hand.
//
// Product 2.2 UI strings. Regenerate after editing
// GamePedia/Resources/Localization/<lang>.lproj/Localizable.strings:
//
//     python3 scripts/generate-product22-l10n.py
//
// The script reads only keys prefixed "product22." and fails if the four
// languages do not declare exactly the same key set. See the script's own
// header for why the repository's SwiftGen config is not used here.
//
// UI chrome only. Game titles, developer names, platform names and article
// headlines are server content and must never be routed through L10n.

import Foundation

extension L10n {
  enum Product22 {
    enum Today {
      /// 오늘의 플레이
      static let title = L10n.tr("Localizable", "product22.today.title")
      /// 잠시 전에 받은 정보예요
      static let stale = L10n.tr("Localizable", "product22.today.stale")
      /// 새로고침
      static let refresh = L10n.tr("Localizable", "product22.today.refresh")
      /// 일부 항목을 불러오지 못했어요. 나머지는 정상이에요.
      static let partialNotice = L10n.tr("Localizable", "product22.today.partialNotice")
    }

    enum Section {
      /// 지금은 불러올 수 없어요
      static let unavailable = L10n.tr("Localizable", "product22.section.unavailable")
      /// 이 항목만 다시 시도
      static let retry = L10n.tr("Localizable", "product22.section.retry")
      /// 이 기능은 지금 제공되지 않아요
      static let disabled = L10n.tr("Localizable", "product22.section.disabled")
      /// 아직 보여드릴 내용이 없어요
      static let empty = L10n.tr("Localizable", "product22.section.empty")
      /// 지금 뭐 하지?
      static let playCompass = L10n.tr("Localizable", "product22.section.playCompass")
      /// 내 플레이 성향
      static let gameDNA = L10n.tr("Localizable", "product22.section.gameDNA")
      /// 관심 게임 소식
      static let gameBriefing = L10n.tr("Localizable", "product22.section.gameBriefing")
      /// 아직 시작 못 한 게임
      static let backlogRescue = L10n.tr("Localizable", "product22.section.backlogRescue")
      /// 스포일러 없는 시작 가이드
      static let spoilerFreeStartGuide = L10n.tr("Localizable", "product22.section.spoilerFreeStartGuide")
      /// 매거진
      static let editorialCuration = L10n.tr("Localizable", "product22.section.editorialCuration")
      /// 이번 달 돌아보기
      static let monthlyReplay = L10n.tr("Localizable", "product22.section.monthlyReplay")
      /// 친구 활동
      static let friendActivity = L10n.tr("Localizable", "product22.section.friendActivity")
    }

    enum Compass {
      /// 지금 할 게임 찾기
      static let cta = L10n.tr("Localizable", "product22.compass.cta")
      /// 보유 중인 게임에서만 골라요
      static let ownedOnly = L10n.tr("Localizable", "product22.compass.ownedOnly")
      /// 설치 여부는 확인하지 않아요
      static let installUnknown = L10n.tr("Localizable", "product22.compass.installUnknown")
      /// 라이브러리 정보가 최신이 아닐 수 있어요
      static let stale = L10n.tr("Localizable", "product22.compass.stale")
      /// 플레이 중이거나 대기 중인 게임이 아직 없어요
      static let emptyNoOwned = L10n.tr("Localizable", "product22.compass.emptyNoOwned")
      /// 조건에 맞는 게임을 찾지 못했어요. 시간이나 조건을 바꿔 보세요.
      static let emptyNoMatch = L10n.tr("Localizable", "product22.compass.emptyNoMatch")
      /// 참고용 추천이에요
      static let confidenceLow = L10n.tr("Localizable", "product22.compass.confidenceLow")
      /// 스토어에서 확인된 보유
      static let ownershipVerified = L10n.tr("Localizable", "product22.compass.ownershipVerified")
      /// 직접 등록한 보유 정보
      static let ownershipUnverified = L10n.tr("Localizable", "product22.compass.ownershipUnverified")
    }

    enum Reason {
      /// 가진 시간에 딱 맞아요
      static let fitsAvailableTime = L10n.tr("Localizable", "product22.reason.fitsAvailableTime")
      /// 시간이 남을 만큼 짧아요
      static let shorterThanAvailableTime = L10n.tr("Localizable", "product22.reason.shorterThanAvailableTime")
      /// 이어서 하기 좋아요
      static let alreadyInProgress = L10n.tr("Localizable", "product22.reason.alreadyInProgress")
      /// 새로 시작하기 좋아요
      static let freshStartAvailable = L10n.tr("Localizable", "product22.reason.freshStartAvailable")
      /// 가장 오래 기다린 게임이에요
      static let backlogOldestUntouched = L10n.tr("Localizable", "product22.reason.backlogOldestUntouched")
      /// 최근에 플레이했어요
      static let recentlyPlayed = L10n.tr("Localizable", "product22.reason.recentlyPlayed")
      /// 한동안 손대지 않았어요
      static let notPlayedRecently = L10n.tr("Localizable", "product22.reason.notPlayedRecently")
      /// 즐겨 하는 장르예요
      static let genreAffinityMatch = L10n.tr("Localizable", "product22.reason.genreAffinityMatch")
      /// 혼자 하기 좋아요
      static let soloFriendly = L10n.tr("Localizable", "product22.reason.soloFriendly")
      /// 같이 하기 좋아요
      static let partyFriendly = L10n.tr("Localizable", "product22.reason.partyFriendly")
      /// 가볍게 즐기기 좋아요
      static let lowEnergyFriendly = L10n.tr("Localizable", "product22.reason.lowEnergyFriendly")
      /// 집중해서 즐기기 좋아요
      static let highEnergyFriendly = L10n.tr("Localizable", "product22.reason.highEnergyFriendly")
      /// 편안한 선택이에요
      static let comfortPick = L10n.tr("Localizable", "product22.reason.comfortPick")
      /// 도전적인 선택이에요
      static let challengePick = L10n.tr("Localizable", "product22.reason.challengePick")
      /// 지금 플랫폼에서 즐길 수 있어요
      static let platformAvailable = L10n.tr("Localizable", "product22.reason.platformAvailable")
      /// 플랫폼에서 이용 가능해요
      static let installedOnPlatform = L10n.tr("Localizable", "product22.reason.installedOnPlatform")
      /// 스팀에 보유 중이에요
      static let ownedOnSteam = L10n.tr("Localizable", "product22.reason.ownedOnSteam")
      /// 친구도 가지고 있어요
      static let friendOwnedOverlap = L10n.tr("Localizable", "product22.reason.friendOwnedOverlap")
      /// 최근에 미뤄 둬서 순위를 낮췄어요
      static let snoozedRecentlyDeprioritized = L10n.tr("Localizable", "product22.reason.snoozedRecentlyDeprioritized")
    }

    enum Basis {
      /// 내 기록 기준
      static let playlogMedian = L10n.tr("Localizable", "product22.basis.playlogMedian")
      /// 일반적인 플레이 시간 기준
      static let catalogTypicalSession = L10n.tr("Localizable", "product22.basis.catalogTypicalSession")
      /// 짧게 즐기는 장르 기준
      static let genreShortSession = L10n.tr("Localizable", "product22.basis.genreShortSession")
      /// 길게 즐기는 장르 기준
      static let genreLongSession = L10n.tr("Localizable", "product22.basis.genreLongSession")
      /// 기본 추정치
      static let defaultEstimate = L10n.tr("Localizable", "product22.basis.defaultEstimate")
    }

    enum Dna {
      /// 내 기록을 그대로 계산한 결과예요
      static let deterministic = L10n.tr("Localizable", "product22.dna.deterministic")
      /// 판단할 기록이 아직 부족해요
      static let needsMoreData = L10n.tr("Localizable", "product22.dna.needsMoreData")
      /// 플레이 기록을 남기면 더 정확해져요
      static let addPlaylog = L10n.tr("Localizable", "product22.dna.addPlaylog")
    }

    enum Replay {
      /// 이 달에는 기록이 없어요
      static let empty = L10n.tr("Localizable", "product22.replay.empty")
      /// 일부 기록은 계산에 넣지 못했어요
      static let missingData = L10n.tr("Localizable", "product22.replay.missingData")
      /// 시간이 없는 기록이 있어 실제보다 적을 수 있어요
      static let minutesPartial = L10n.tr("Localizable", "product22.replay.minutesPartial")
    }

    enum Article {
      /// 정정됨
      static let corrected = L10n.tr("Localizable", "product22.article.corrected")
      /// 무엇이 바뀌었나요
      static let changeNote = L10n.tr("Localizable", "product22.article.changeNote")
      /// 출처
      static let sources = L10n.tr("Localizable", "product22.article.sources")
      /// 수집 시각
      static let sourceFetchedAt = L10n.tr("Localizable", "product22.article.sourceFetchedAt")
      /// 안전하지 않은 링크라 열 수 없어요
      static let sourceNotOpenable = L10n.tr("Localizable", "product22.article.sourceNotOpenable")
      /// 이미지 사용 권리가 확인되지 않아 표시하지 않아요
      static let heroWithheld = L10n.tr("Localizable", "product22.article.heroWithheld")
      /// 관련 게임
      static let relatedGames = L10n.tr("Localizable", "product22.article.relatedGames")
      /// 기사 읽기
      static let readMore = L10n.tr("Localizable", "product22.article.readMore")
    }

    enum Catalog {
      /// 게임 카탈로그
      static let searchTitle = L10n.tr("Localizable", "product22.catalog.searchTitle")
      /// 게임 이름을 입력하세요
      static let searchPlaceholder = L10n.tr("Localizable", "product22.catalog.searchPlaceholder")
      /// 찾고 싶은 게임을 검색해 보세요
      static let searchPrompt = L10n.tr("Localizable", "product22.catalog.searchPrompt")
      /// 검색 결과가 없어요
      static let noResults = L10n.tr("Localizable", "product22.catalog.noResults")
      /// 찾는 게임이 없나요? 빠르게 등록
      static let quickAddPrompt = L10n.tr("Localizable", "product22.catalog.quickAddPrompt")
      /// 소식 받기
      static let follow = L10n.tr("Localizable", "product22.catalog.follow")
      /// 소식 그만 받기
      static let unfollow = L10n.tr("Localizable", "product22.catalog.unfollow")
      /// 정보 수정 제안
      static let correction = L10n.tr("Localizable", "product22.catalog.correction")
      /// 제안이 접수됐어요. 검토 후 반영됩니다.
      static let correctionPending = L10n.tr("Localizable", "product22.catalog.correctionPending")
      /// 수정할 항목
      static let correctionFieldPath = L10n.tr("Localizable", "product22.catalog.correctionFieldPath")
      /// 올바른 값
      static let correctionValue = L10n.tr("Localizable", "product22.catalog.correctionValue")
      /// 출처 링크 (선택)
      static let correctionSource = L10n.tr("Localizable", "product22.catalog.correctionSource")
      /// 원제
      static let originalTitle = L10n.tr("Localizable", "product22.catalog.originalTitle")
      /// 다른 이름
      static let aliases = L10n.tr("Localizable", "product22.catalog.aliases")
      /// 국가별 서비스
      static let regionalReleases = L10n.tr("Localizable", "product22.catalog.regionalReleases")
      /// 정보 출처
      static let evidence = L10n.tr("Localizable", "product22.catalog.evidence")
      /// 플레이 기록
      static let playlogEntry = L10n.tr("Localizable", "product22.catalog.playlogEntry")
    }

    enum Provenance {
      /// 확인된 정보
      static let verified = L10n.tr("Localizable", "product22.provenance.verified")
      /// 사용자가 입력한 정보
      static let asserted = L10n.tr("Localizable", "product22.provenance.asserted")
      /// 아직 확인되지 않음
      static let unconfirmed = L10n.tr("Localizable", "product22.provenance.unconfirmed")
    }

    enum Service {
      /// 출시 예정
      static let announced = L10n.tr("Localizable", "product22.service.announced")
      /// 사전 등록
      static let preRegistration = L10n.tr("Localizable", "product22.service.preRegistration")
      /// 서비스 중
      static let live = L10n.tr("Localizable", "product22.service.live")
      /// 점검 중
      static let maintenance = L10n.tr("Localizable", "product22.service.maintenance")
      /// 서비스 종료 예정
      static let sunsetAnnounced = L10n.tr("Localizable", "product22.service.sunsetAnnounced")
      /// 서비스 종료
      static let shutdown = L10n.tr("Localizable", "product22.service.shutdown")
    }

    enum Publication {
      /// 나만 보는 등록
      static let `private` = L10n.tr("Localizable", "product22.publication.private")
      /// 공개 검토 대기 중
      static let pendingReview = L10n.tr("Localizable", "product22.publication.pendingReview")
      /// 공개됨
      static let published = L10n.tr("Localizable", "product22.publication.published")
      /// 반려됨
      static let rejected = L10n.tr("Localizable", "product22.publication.rejected")
    }

    enum QuickAdd {
      /// 게임 빠르게 등록
      static let title = L10n.tr("Localizable", "product22.quickAdd.title")
      /// 게임 이름, 공식 사이트, App Store 또는 Google Play 주소를 입력하세요
      static let inputPrompt = L10n.tr("Localizable", "product22.quickAdd.inputPrompt")
      /// 예: 게임 이름 또는 스토어 주소
      static let inputPlaceholder = L10n.tr("Localizable", "product22.quickAdd.inputPlaceholder")
      /// 입력한 문장은 저장하지 않아요
      static let inputNotStored = L10n.tr("Localizable", "product22.quickAdd.inputNotStored")
      /// 국가
      static let region = L10n.tr("Localizable", "product22.quickAdd.region")
      /// 플랫폼 (선택)
      static let platformHint = L10n.tr("Localizable", "product22.quickAdd.platformHint")
      /// 확인해 보기
      static let preview = L10n.tr("Localizable", "product22.quickAdd.preview")
      /// 이미 등록된 게임
      static let existingCandidates = L10n.tr("Localizable", "product22.quickAdd.existingCandidates")
      /// 새로 등록하기
      static let newDraft = L10n.tr("Localizable", "product22.quickAdd.newDraft")
      /// 이 게임으로 연결
      static let linkExisting = L10n.tr("Localizable", "product22.quickAdd.linkExisting")
      /// 게임 이름을 직접 확인해 주세요
      static let titleRequired = L10n.tr("Localizable", "product22.quickAdd.titleRequired")
      /// 아래 내용을 확인한 뒤 등록해 주세요
      static let confirmFields = L10n.tr("Localizable", "product22.quickAdd.confirmFields")
      /// 확인이 필요해요
      static let needsConfirmation = L10n.tr("Localizable", "product22.quickAdd.needsConfirmation")
      /// 자동으로 추정한 값이에요. 맞는지 확인해 주세요.
      static let aiInferred = L10n.tr("Localizable", "product22.quickAdd.aiInferred")
      /// 자동 확인에 실패해서 직접 입력이 필요해요
      static let aiFallback = L10n.tr("Localizable", "product22.quickAdd.aiFallback")
      /// 나만 보는 목록에 등록
      static let registerPrivate = L10n.tr("Localizable", "product22.quickAdd.registerPrivate")
      /// 공개 목록 등재 요청하기
      static let requestPublicReview = L10n.tr("Localizable", "product22.quickAdd.requestPublicReview")
      /// 공개 등재는 검토를 거쳐요. 요청해도 바로 공개되지 않아요.
      static let publicReviewNote = L10n.tr("Localizable", "product22.quickAdd.publicReviewNote")
      /// 나만 보는 목록에 등록했어요
      static let doneRegistered = L10n.tr("Localizable", "product22.quickAdd.doneRegistered")
      /// 이미 있던 게임에 연결했어요
      static let doneLinked = L10n.tr("Localizable", "product22.quickAdd.doneLinked")
      /// 공개 등재를 요청했어요. 검토 결과를 기다려 주세요.
      static let donePendingReview = L10n.tr("Localizable", "product22.quickAdd.donePendingReview")
      /// 카탈로그에서 찾아보기
      static let findInCatalog = L10n.tr("Localizable", "product22.quickAdd.findInCatalog")
      /// 확인 결과가 만료됐어요. 다시 확인해 주세요.
      static let expired = L10n.tr("Localizable", "product22.quickAdd.expired")
      /// 오늘 등록 요청을 너무 많이 했어요. 잠시 후 다시 시도해 주세요.
      static let quotaExceeded = L10n.tr("Localizable", "product22.quickAdd.quotaExceeded")
      /// 이미 등록된 게임과 정보가 겹쳐요. 위 목록에서 골라 주세요.
      static let identityConflict = L10n.tr("Localizable", "product22.quickAdd.identityConflict")
      /// 입력한 내용을 확인해 주세요
      static let invalidInput = L10n.tr("Localizable", "product22.quickAdd.invalidInput")
      /// 스토어에서 확인된 같은 게임
      static let matchExact = L10n.tr("Localizable", "product22.quickAdd.matchExact")
      /// 비슷하지만 아직 확인되지 않았어요
      static let matchUnverified = L10n.tr("Localizable", "product22.quickAdd.matchUnverified")
    }

    enum Playlog {
      /// 플레이 기록
      static let title = L10n.tr("Localizable", "product22.playlog.title")
      /// 아직 기록이 없어요
      static let empty = L10n.tr("Localizable", "product22.playlog.empty")
      /// 기록 추가
      static let add = L10n.tr("Localizable", "product22.playlog.add")
      /// 기록 수정
      static let edit = L10n.tr("Localizable", "product22.playlog.edit")
      /// 기록 삭제
      static let delete = L10n.tr("Localizable", "product22.playlog.delete")
      /// 달력
      static let calendar = L10n.tr("Localizable", "product22.playlog.calendar")
      /// 언제 했나요
      static let playedAt = L10n.tr("Localizable", "product22.playlog.playedAt")
      /// 얼마나 했나요 (분)
      static let duration = L10n.tr("Localizable", "product22.playlog.duration")
      /// 진행도 (%)
      static let progress = L10n.tr("Localizable", "product22.playlog.progress")
      /// 기분
      static let mood = L10n.tr("Localizable", "product22.playlog.mood")
      /// 어떻게 끝냈나요
      static let outcome = L10n.tr("Localizable", "product22.playlog.outcome")
      /// 공개 범위
      static let visibility = L10n.tr("Localizable", "product22.playlog.visibility")
      /// 메모
      static let note = L10n.tr("Localizable", "product22.playlog.note")
      /// 메모와 기분은 나만 볼 수 있어요
      static let notePrivate = L10n.tr("Localizable", "product22.playlog.notePrivate")
      /// 저장
      static let save = L10n.tr("Localizable", "product22.playlog.save")
      /// 저장하지 못했어요. 다시 시도하면 중복 없이 저장돼요.
      static let saveFailed = L10n.tr("Localizable", "product22.playlog.saveFailed")
      /// 이 기록을 삭제할까요?
      static let deleteConfirm = L10n.tr("Localizable", "product22.playlog.deleteConfirm")
      /// 시간 미기록
      static let durationUnknown = L10n.tr("Localizable", "product22.playlog.durationUnknown")
      /// 이 날의 기록
      static let sessionsOnDay = L10n.tr("Localizable", "product22.playlog.sessionsOnDay")
    }

    enum Outcome {
      /// 계속 진행 중
      static let `continue` = L10n.tr("Localizable", "product22.outcome.continue")
      /// 잠시 멈춤
      static let paused = L10n.tr("Localizable", "product22.outcome.paused")
      /// 그만둠
      static let dropped = L10n.tr("Localizable", "product22.outcome.dropped")
      /// 끝까지 함
      static let completed = L10n.tr("Localizable", "product22.outcome.completed")
    }

    enum Mood {
      /// 느긋함
      static let relaxed = L10n.tr("Localizable", "product22.mood.relaxed")
      /// 몰입함
      static let focused = L10n.tr("Localizable", "product22.mood.focused")
      /// 신남
      static let excited = L10n.tr("Localizable", "product22.mood.excited")
      /// 지루함
      static let bored = L10n.tr("Localizable", "product22.mood.bored")
      /// 답답함
      static let frustrated = L10n.tr("Localizable", "product22.mood.frustrated")
      /// 추억에 잠김
      static let nostalgic = L10n.tr("Localizable", "product22.mood.nostalgic")
    }

    enum Visibility {
      /// 나만 보기
      static let `private` = L10n.tr("Localizable", "product22.visibility.private")
      /// 친구에게 공개
      static let friends = L10n.tr("Localizable", "product22.visibility.friends")
      /// 전체 공개
      static let `public` = L10n.tr("Localizable", "product22.visibility.public")
    }
  }
}

// swiftlint:enable all
