// swiftlint:disable all
// Generated by scripts/generate-product22-l10n.py — do not edit by hand.
//
// Product 2.2 UI strings. Regenerate after editing
// GamePedia/Resources/Localization/<lang>.lproj/Localizable.strings:
//
//     python3 scripts/generate-product22-l10n.py
//
// The script reads only keys prefixed "product22." and fails if the four
// languages do not declare exactly the same key set. See the script's own
// header for why the repository's SwiftGen config is not used here.
//
// UI chrome only. Game titles, developer names, platform names and article
// headlines are server content and must never be routed through L10n.

import Foundation

extension L10n {
  enum Product22 {
    enum Today {
      /// 오늘의 플레이
      static let title = L10n.tr("Localizable", "product22.today.title")
      /// 잠시 전에 받은 정보예요
      static let stale = L10n.tr("Localizable", "product22.today.stale")
      /// 새로고침
      static let refresh = L10n.tr("Localizable", "product22.today.refresh")
      /// 일부 항목을 불러오지 못했어요. 나머지는 정상이에요.
      static let partialNotice = L10n.tr("Localizable", "product22.today.partialNotice")
    }

    enum Section {
      /// 지금은 불러올 수 없어요
      static let unavailable = L10n.tr("Localizable", "product22.section.unavailable")
      /// 이 항목만 다시 시도
      static let retry = L10n.tr("Localizable", "product22.section.retry")
      /// 이 기능은 지금 제공되지 않아요
      static let disabled = L10n.tr("Localizable", "product22.section.disabled")
      /// 아직 보여드릴 내용이 없어요
      static let empty = L10n.tr("Localizable", "product22.section.empty")
      /// 지금 뭐 하지?
      static let playCompass = L10n.tr("Localizable", "product22.section.playCompass")
      /// 내 플레이 성향
      static let gameDNA = L10n.tr("Localizable", "product22.section.gameDNA")
      /// 관심 게임 소식
      static let gameBriefing = L10n.tr("Localizable", "product22.section.gameBriefing")
      /// 아직 시작 못 한 게임
      static let backlogRescue = L10n.tr("Localizable", "product22.section.backlogRescue")
      /// 스포일러 없는 시작 가이드
      static let spoilerFreeStartGuide = L10n.tr("Localizable", "product22.section.spoilerFreeStartGuide")
      /// 매거진
      static let editorialCuration = L10n.tr("Localizable", "product22.section.editorialCuration")
      /// 이번 달 돌아보기
      static let monthlyReplay = L10n.tr("Localizable", "product22.section.monthlyReplay")
      /// 친구 활동
      static let friendActivity = L10n.tr("Localizable", "product22.section.friendActivity")
    }

    enum Compass {
      /// 지금 할 게임 찾기
      static let cta = L10n.tr("Localizable", "product22.compass.cta")
      /// 보유 중인 게임에서만 골라요
      static let ownedOnly = L10n.tr("Localizable", "product22.compass.ownedOnly")
      /// 설치 여부는 확인하지 않아요
      static let installUnknown = L10n.tr("Localizable", "product22.compass.installUnknown")
      /// 라이브러리 정보가 최신이 아닐 수 있어요
      static let stale = L10n.tr("Localizable", "product22.compass.stale")
      /// 플레이 중이거나 대기 중인 게임이 아직 없어요
      static let emptyNoOwned = L10n.tr("Localizable", "product22.compass.emptyNoOwned")
      /// 조건에 맞는 게임을 찾지 못했어요. 시간이나 조건을 바꿔 보세요.
      static let emptyNoMatch = L10n.tr("Localizable", "product22.compass.emptyNoMatch")
      /// 참고용 추천이에요
      static let confidenceLow = L10n.tr("Localizable", "product22.compass.confidenceLow")
      /// 스토어에서 확인된 보유
      static let ownershipVerified = L10n.tr("Localizable", "product22.compass.ownershipVerified")
      /// 직접 등록한 보유 정보
      static let ownershipUnverified = L10n.tr("Localizable", "product22.compass.ownershipUnverified")
    }

    enum Reason {
      /// 가진 시간에 딱 맞아요
      static let fitsAvailableTime = L10n.tr("Localizable", "product22.reason.fitsAvailableTime")
      /// 시간이 남을 만큼 짧아요
      static let shorterThanAvailableTime = L10n.tr("Localizable", "product22.reason.shorterThanAvailableTime")
      /// 이어서 하기 좋아요
      static let alreadyInProgress = L10n.tr("Localizable", "product22.reason.alreadyInProgress")
      /// 새로 시작하기 좋아요
      static let freshStartAvailable = L10n.tr("Localizable", "product22.reason.freshStartAvailable")
      /// 가장 오래 기다린 게임이에요
      static let backlogOldestUntouched = L10n.tr("Localizable", "product22.reason.backlogOldestUntouched")
      /// 최근에 플레이했어요
      static let recentlyPlayed = L10n.tr("Localizable", "product22.reason.recentlyPlayed")
      /// 한동안 손대지 않았어요
      static let notPlayedRecently = L10n.tr("Localizable", "product22.reason.notPlayedRecently")
      /// 즐겨 하는 장르예요
      static let genreAffinityMatch = L10n.tr("Localizable", "product22.reason.genreAffinityMatch")
      /// 혼자 하기 좋아요
      static let soloFriendly = L10n.tr("Localizable", "product22.reason.soloFriendly")
      /// 같이 하기 좋아요
      static let partyFriendly = L10n.tr("Localizable", "product22.reason.partyFriendly")
      /// 가볍게 즐기기 좋아요
      static let lowEnergyFriendly = L10n.tr("Localizable", "product22.reason.lowEnergyFriendly")
      /// 집중해서 즐기기 좋아요
      static let highEnergyFriendly = L10n.tr("Localizable", "product22.reason.highEnergyFriendly")
      /// 편안한 선택이에요
      static let comfortPick = L10n.tr("Localizable", "product22.reason.comfortPick")
      /// 도전적인 선택이에요
      static let challengePick = L10n.tr("Localizable", "product22.reason.challengePick")
      /// 지금 플랫폼에서 즐길 수 있어요
      static let platformAvailable = L10n.tr("Localizable", "product22.reason.platformAvailable")
      /// 플랫폼에서 이용 가능해요
      static let installedOnPlatform = L10n.tr("Localizable", "product22.reason.installedOnPlatform")
      /// 스팀에 보유 중이에요
      static let ownedOnSteam = L10n.tr("Localizable", "product22.reason.ownedOnSteam")
      /// 친구도 가지고 있어요
      static let friendOwnedOverlap = L10n.tr("Localizable", "product22.reason.friendOwnedOverlap")
      /// 최근에 미뤄 둬서 순위를 낮췄어요
      static let snoozedRecentlyDeprioritized = L10n.tr("Localizable", "product22.reason.snoozedRecentlyDeprioritized")
    }

    enum Basis {
      /// 내 기록 기준
      static let playlogMedian = L10n.tr("Localizable", "product22.basis.playlogMedian")
      /// 일반적인 플레이 시간 기준
      static let catalogTypicalSession = L10n.tr("Localizable", "product22.basis.catalogTypicalSession")
      /// 짧게 즐기는 장르 기준
      static let genreShortSession = L10n.tr("Localizable", "product22.basis.genreShortSession")
      /// 길게 즐기는 장르 기준
      static let genreLongSession = L10n.tr("Localizable", "product22.basis.genreLongSession")
      /// 기본 추정치
      static let defaultEstimate = L10n.tr("Localizable", "product22.basis.defaultEstimate")
    }

    enum Dna {
      /// 내 기록을 그대로 계산한 결과예요
      static let deterministic = L10n.tr("Localizable", "product22.dna.deterministic")
      /// 판단할 기록이 아직 부족해요
      static let needsMoreData = L10n.tr("Localizable", "product22.dna.needsMoreData")
      /// 플레이 기록을 남기면 더 정확해져요
      static let addPlaylog = L10n.tr("Localizable", "product22.dna.addPlaylog")
    }

    enum Replay {
      /// 이 달에는 기록이 없어요
      static let empty = L10n.tr("Localizable", "product22.replay.empty")
      /// 일부 기록은 계산에 넣지 못했어요
      static let missingData = L10n.tr("Localizable", "product22.replay.missingData")
      /// 시간이 없는 기록이 있어 실제보다 적을 수 있어요
      static let minutesPartial = L10n.tr("Localizable", "product22.replay.minutesPartial")
    }

    enum Article {
      /// 정정됨
      static let corrected = L10n.tr("Localizable", "product22.article.corrected")
      /// 무엇이 바뀌었나요
      static let changeNote = L10n.tr("Localizable", "product22.article.changeNote")
      /// 출처
      static let sources = L10n.tr("Localizable", "product22.article.sources")
      /// 수집 시각
      static let sourceFetchedAt = L10n.tr("Localizable", "product22.article.sourceFetchedAt")
      /// 안전하지 않은 링크라 열 수 없어요
      static let sourceNotOpenable = L10n.tr("Localizable", "product22.article.sourceNotOpenable")
      /// 이미지 사용 권리가 확인되지 않아 표시하지 않아요
      static let heroWithheld = L10n.tr("Localizable", "product22.article.heroWithheld")
      /// 관련 게임
      static let relatedGames = L10n.tr("Localizable", "product22.article.relatedGames")
      /// 기사 읽기
      static let readMore = L10n.tr("Localizable", "product22.article.readMore")
    }
  }
}

// swiftlint:enable all
